services:
  app:
    build:
      context: ..
      dockerfile: ./docker-production/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    volumes:
      - cache_data:/var/www/html/bootstrap/cache
      - storage_data:/var/www/html/storage
    env_file:
      - ./.env.prod
    environment:
      - "APP_ENV=${APP_ENV:-production}"
      - "APP_DEBUG=${APP_DEBUG:-false}"
    networks:
      - app-network
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: "mariadb:12"
    container_name: mariadb_container
    command: [
      '--performance-schema=on',
      '--innodb-buffer-pool-size=256M',
      '--innodb-log-file-size=128M',
      '--max-connections=100'
    ]
    env_file:
      - ./.env.bd
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE}"
      MARIADB_USER: "${MARIADB_USERNAME}"
      MARIADB_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_ALLOW_EMPTY_PASSWORD: "yes"
      MARIADB_ROOT_PASSWORD: "${MARIADB_PASSWORD}"
      MARIADB_PORT: "${MARIADB_PORT}"
      MARIADB_PERFORMANCE_SCHEMA: 1
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  redis:
    image: "redis:alpine"
    env_file:
      - prod.env
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
  redis_data:
    name: redis_data
  storage_data:
    name: storage_data
  cache_data:
    name: cache_data

